#!/usr/bin/env bash

function install {
    npm install
}

function build {
    npm run build
}

function watch {
    npm run watch
}

function format {
    npm run format
}

function t {
    jing -c schema/book.rnc docs/didactics-reports/report-on-the-little-typer.xml
}

function main {
    for TASK in $@
    do
        $TASK
    done
}

main $@
