#!/usr/bin/env bash

function t {
    test-src node js
}

function test-src {
    prog=$1
    ext=$2

    for file in $(find . | grep -v "node_modules/" | grep "./*/src/" | grep "\.test.*$" | grep "\.${ext}$")
    do
        echo ""
        echo "[test] $file"
        if ! time $prog $file
        then
            exit 1
        fi
    done
}

function main {
    for TASK in $@
    do
        $TASK
    done
}

main $@
